- name: Install pre-requisite packages
  yum:
    name: "{{item}}"
    state: latest
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: Add Docker CE repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum:
    name: "{{item}}"
    state: latest
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io

- name: Start and enable the Docker daemon
  service:
    name: docker
    state: started
    enabled: yes

- name: install python docker py
  yum:
    name: python-docker-py
    update_cache: yes
    state: latest
