- name: Install Docker
  apt:
    name: "{{item}}"
    state: latest
  loop:
    - docker.io
    - python3-docker
  become: true

- name: Start and enable the Docker daemon
  service:
    name: docker
    state: started
    enabled: yes
