---
# tasks file for oracle_db

- name: Oracle Role
  set_fact:
    role_oracle_started: yes
  tags:
    - always

- block:
    - name: make sure docker is running
      import_tasks: docker.yml

    - name: Install collection from Ansible Galaxy
      command: ansible-galaxy collection install community.docker
      changed_when: false

    - name: Check docker image current status
      docker_image_info:
        name: oracle/database:18.4.0-xe
      register: last_result
      ignore_errors: yes

    - name: Check if oracle database container tarball exists
      stat:
        path: /vagrant/oracle_database.tar.gz
      register: stat_oracle_database_result

    - name: Check if oracle linux container tarball exists
      stat:
        path: /vagrant/oracle_linux.tar.gz
      register: stat_oracle_linux_result

    - name: load database container from tarball
      docker_image:
        name: oracle/database:18.4.0-xe
        load_path: /vagrant/oracle_database.tar.gz
        state: present
        source: load
      when: last_result is defined and last_result.images == [] and stat_oracle_database_result.stat.exists and stat_oracle_linux_result.stat.exists

    - name: load oraclelinux container from tarball
      docker_image:
        name: oraclelinux:7-slim
        load_path: /vagrant/oracle_linux.tar.gz
        state: present
        source: load
      when: last_result is defined and last_result.images == [] and stat_oracle_database_result.stat.exists and stat_oracle_linux_result.stat.exists

    - name: Import prepare
      import_tasks: prepare.yml
      when: last_result is defined and last_result.images == [] and not stat_oracle_database_result.stat.exists and not stat_oracle_linux_result.stat.exists

    - name: Check database docker image status if image was build or installed from tarball
      docker_image_info:
        name: oracle/database:18.4.0-xe
      ignore_errors: no
      when: last_result is defined and last_result.images == []

    - name: Check oraclelinux docker image status  if image was build or installed from tarball
      docker_image_info:
        name: oraclelinux:7-slim
      ignore_errors: no
      when: last_result is defined and last_result.images == []

    - name: Archive database container image as a tarball
      docker_image:
        name: oracle/database:18.4.0-xe
        archive_path: /vagrant/oracle_database.tar
        source: pull
        state: present
      when: not stat_oracle_database_result.stat.exists

    - name: Compress database container image tarball
      archive:
        path: /vagrant/oracle_database.tar
        dest: /vagrant/oracle_database.tar.gz
        format: gz
      when: not stat_oracle_database_result.stat.exists

    - name: Delete database container image tarball
      file:
        path: /vagrant/oracle_database.tar
        state: absent

    - name: Archive oraclelinux container image as a tarball
      docker_image:
        name: oraclelinux:7-slim
        archive_path: /vagrant/oracle_linux.tar
        source: pull
        state: present
      when: not stat_oracle_linux_result.stat.exists

    - name: Compress oraclelinux container image tarball
      archive:
        path: /vagrant/oracle_linux.tar
        dest: /vagrant/oracle_linux.tar.gz
        format: gz
      when: not stat_oracle_linux_result.stat.exists

    - name: Delete oraclelinux container image tarball
      file:
        path: /vagrant/oracle_linux.tar
        state: absent



