- name: install git
  apt:
    name: git
    state: latest
  become: true

- name: Clone docker repository
  git:
    repo: https://github.com/oracle/docker-images.git
    dest: /home/vagrant/oracle-xe

- name: build Oracle 18c XE docker image
  shell: ./buildContainerImage.sh -v 18.4.0 -x
  args:
    chdir: /home/vagrant/oracle-xe/OracleDatabase/SingleInstance/dockerfiles
    executable: /bin/sh
  become: true
