- name: install git
  apt:
    name: git
    state: present
  become: true

- name: Clone docker repository
  git:
    repo: https://github.com/oracle/docker-images.git
    dest: /home/vagrant/oracle-xe
    version: 65261b950a9571d99bbf1bdef067e1ada25040bd

- name: build Oracle {{ oracle_version }} XE docker image
  command:
    argv:
      - /home/vagrant/oracle-xe/OracleDatabase/SingleInstance/dockerfiles/buildContainerImage.sh
      - -v
      - '{{ oracle_version }}'
      - -x
  become: true
